In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df=pd.read_csv("C:/Users/nitin/Documents/sales_data.csv")

In [3]:
df.head()

   OrderID        Date     Product     Category  Quantity  UnitPrice
0     1031  2026-01-01  Smartphone  Electronics         3        800
1     1100  2026-01-02  Headphones  Accessories         2        150
2     1028  2026-01-02      Laptop  Electronics         2       1200
3     1089  2026-01-02      Laptop  Electronics         3       1200
4     1023  2026-01-02      Tablet  Electronics         4        450

In [5]:
df.tail()

    OrderID        Date     Product     Category  Quantity  UnitPrice
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

In [7]:
df.columns

Index(['OrderID', 'Date', 'Product', 'Category', 'Quantity', 'UnitPrice'], dtype='str')

In [6]:
df.shape

(100, 6)

In [10]:
df["OrderID"]

0     1031
1     1100
2     1028
3     1089
4     1023
      ...
95    1026
96    1090
97    1049
98    1046
99    1047
Name: OrderID, Length: 100, dtype: int64

In [11]:
df.loc[0]

OrderID             1031
Date          2026-01-01
Product       Smartphone
Category     Electronics
Quantity               3
UnitPrice            800
Name: 0, dtype: object

In [15]:
df.loc[0:4,["Product","UnitPrice"]]

      Product  UnitPrice
0  Smartphone        800
1  Headphones        150
2      Laptop       1200
3      Laptop       1200
4      Tablet        450

In [7]:
df.loc[0,"Product"]

'Smartphone'

In [8]:
df.loc[0:4]

   OrderID        Date     Product     Category  Quantity  UnitPrice
0     1031  2026-01-01  Smartphone  Electronics         3        800
1     1100  2026-01-02  Headphones  Accessories         2        150
2     1028  2026-01-02      Laptop  Electronics         2       1200
3     1089  2026-01-02      Laptop  Electronics         3       1200
4     1023  2026-01-02      Tablet  Electronics         4        450

In [9]:
df.loc[0]

OrderID             1031
Date          2026-01-01
Product       Smartphone
Category     Electronics
Quantity               3
UnitPrice            800
Name: 0, dtype: object

In [10]:
df.iloc[0:4]

   OrderID        Date     Product     Category  Quantity  UnitPrice
0     1031  2026-01-01  Smartphone  Electronics         3        800
1     1100  2026-01-02  Headphones  Accessories         2        150
2     1028  2026-01-02      Laptop  Electronics         2       1200
3     1089  2026-01-02      Laptop  Electronics         3       1200

In [4]:
df.iloc[0]
df.iloc[0:5]


df.iloc[0,2]

'Smartphone'

In [14]:
df[df["Quantity"]<10]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [13]:
df[(df["Quantity"]>2) & (df["UnitPrice"]>1000)]

    OrderID        Date Product     Category  Quantity  UnitPrice
3      1089  2026-01-02  Laptop  Electronics         3       1200
24     1087  2026-01-08  Laptop  Electronics         4       1200
36     1025  2026-01-12  Laptop  Electronics         3       1200
42     1048  2026-01-15  Laptop  Electronics         3       1200
46     1044  2026-01-16  Laptop  Electronics         4       1200
48     1084  2026-01-17  Laptop  Electronics         4       1200
69     1052  2026-01-23  Laptop  Electronics         3       1200
71     1015  2026-01-24  Laptop  Electronics         4       1200
73     1019  2026-01-24  Laptop  Electronics         3       1200
78     1033  2026-01-26  Laptop  Electronics         4       1200
87     1074  2026-01-28  Laptop  Electronics         3       1200

In [22]:
df[(df["UnitPrice"]<1000) | (df["Product"]== "Laptop")]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [19]:
df[df["Category"].isin(["Electronics","Accessories"])]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [23]:
df.loc[df["UnitPrice"]>100,["Product","Category"]]

       Product     Category
0   Smartphone  Electronics
1   Headphones  Accessories
2       Laptop  Electronics
3       Laptop  Electronics
4       Tablet  Electronics
..         ...          ...
95      Tablet  Electronics
96  Headphones  Accessories
97  Smartwatch  Accessories
98  Smartwatch  Accessories
99      Tablet  Electronics

[100 rows x 2 columns]

In [8]:
df.sort_values(["Product"])

    OrderID        Date     Product     Category  Quantity  UnitPrice  Sales
77     1070  2026-01-26  Headphones  Accessories         1        150    150
64     1059  2026-01-21  Headphones  Accessories         2        150    300
65     1034  2026-01-22  Headphones  Accessories         1        150    150
57     1002  2026-01-20  Headphones  Accessories         3        150    450
54     1011  2026-01-19  Headphones  Accessories         2        150    300
..      ...         ...         ...          ...       ...        ...    ...
44     1045  2026-01-15      Tablet  Electronics         3        450   1350
72     1024  2026-01-24      Tablet  Electronics         1        450    450
53     1057  2026-01-19      Tablet  Electronics         2        450    900
84     1029  2026-01-28      Tablet  Electronics         4        450   1800
99     1047  2026-01-30      Tablet  Electronics         3        450   1350

[100 rows x 7 columns]

In [7]:
df["Sales"] =df["Quantity"] * df["UnitPrice"]
df.head()

   OrderID        Date     Product     Category  Quantity  UnitPrice  Sales
0     1031  2026-01-01  Smartphone  Electronics         3        800   2400
1     1100  2026-01-02  Headphones  Accessories         2        150    300
2     1028  2026-01-02      Laptop  Electronics         2       1200   2400
3     1089  2026-01-02      Laptop  Electronics         3       1200   3600
4     1023  2026-01-02      Tablet  Electronics         4        450   1800

In [9]:
df.groupby("Category")["Sales"].min()

Category
Accessories    150
Electronics    450
Name: Sales, dtype: int64

In [10]:
df.groupby("Category")["Sales"].max()

Category
Accessories    1000
Electronics    4800
Name: Sales, dtype: int64

In [16]:
df.groupby("Category")["Sales"].sum()

Category
Accessories     22750
Electronics    127600
Name: Sales, dtype: int64

In [17]:
df.groupby("Category")["Sales"].mean()

Category
Accessories     541.666667
Electronics    2200.000000
Name: Sales, dtype: float64

In [11]:
print(df.sort_values(by="Sales", ascending=True))

    OrderID        Date     Product     Category  Quantity  UnitPrice  Sales
6      1055  2026-01-03  Headphones  Accessories         1        150    150
63     1022  2026-01-21  Headphones  Accessories         1        150    150
70     1012  2026-01-23  Headphones  Accessories         1        150    150
65     1034  2026-01-22  Headphones  Accessories         1        150    150
77     1070  2026-01-26  Headphones  Accessories         1        150    150
..      ...         ...         ...          ...       ...        ...    ...
24     1087  2026-01-08      Laptop  Electronics         4       1200   4800
48     1084  2026-01-17      Laptop  Electronics         4       1200   4800
46     1044  2026-01-16      Laptop  Electronics         4       1200   4800
71     1015  2026-01-24      Laptop  Electronics         4       1200   4800
78     1033  2026-01-26      Laptop  Electronics         4       1200   4800

[100 rows x 7 columns]

In [12]:
print(df.sort_values(by="Sales", ascending=False))

    OrderID        Date     Product     Category  Quantity  UnitPrice  Sales
24     1087  2026-01-08      Laptop  Electronics         4       1200   4800
78     1033  2026-01-26      Laptop  Electronics         4       1200   4800
46     1044  2026-01-16      Laptop  Electronics         4       1200   4800
48     1084  2026-01-17      Laptop  Electronics         4       1200   4800
71     1015  2026-01-24      Laptop  Electronics         4       1200   4800
..      ...         ...         ...          ...       ...        ...    ...
6      1055  2026-01-03  Headphones  Accessories         1        150    150
65     1034  2026-01-22  Headphones  Accessories         1        150    150
63     1022  2026-01-21  Headphones  Accessories         1        150    150
77     1070  2026-01-26  Headphones  Accessories         1        150    150
70     1012  2026-01-23  Headphones  Accessories         1        150    150

[100 rows x 7 columns]

In [15]:
df["Calculated_Sales"] = df["Quantity"] * df["UnitPrice"]